server.port=8082
eureka.client.register.with.eureka=true

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/auths
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# # ============================================
# # PostgreSQL Database Configuration
# # ============================================

# # Configuration JDBC
# spring.datasource.url=jdbc:postgresql://localhost:5432/auth
# spring.datasource.username=postgres
# spring.datasource.password=admin
# spring.datasource.driver-class-name=org.postgresql.Driver



# # ============================================
# # JPA/Hibernate Configuration
# # ============================================

# # Dialecte PostgreSQL
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# # DDL mode (create, update, create-drop, validate, none)
# spring.jpa.hibernate.ddl-auto=update

# # Afficher les requêtes SQL dans les logs
# spring.jpa.show-sql=true