server.port=8083
#config eureka
eureka.client.register.with.eureka=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
#activation de la decouverte dynamique des microservices
#eureka.client.fetch-registry=true
spring.cloud.gateway.discovery.locator.enabled=true
